### ISSUE TITLE
[Enhancement]: Enable the "update branch" button in PRs

### ISSUE THREAD

**Issue by rhoneyager** [JCSDA-internal/ufo-data#16]
## Description
The "update branch" button does not show for PRs in ufo-data.

<img width="966" alt="Screen Shot 2021-06-17 at 12 43 39 PM" src="https://user-images.githubusercontent.com/7389890/122439483-ae6fa480-cf69-11eb-830a-eacb5738226f.png">

This button only shows up in GitHub if status checks are enabled for a repository. If it does not appear, then users become confused and think that data files are missing or outdated, when really their data branch is out of sync. So, I am asking for a fake status check to be added to ufo-data and ioda-data.

**Comment by rhoneyager** [comment]
This affected https://github.com/JCSDA-internal/ufo/pull/1273, https://github.com/JCSDA-internal/ufo/pull/1198, and a few other PRs.

**Comment by mmiesch** [comment]
Thanks @rhoneyager for noticing that.  I changed it for the ufo-data, ioda-data, and fv3-data repos.
