### ISSUE TITLE
Using "ObsFilterData" in GMI_GPM bias correction

### ISSUE THREAD

**Issue by gmao-jjin3** [JCSDA-internal/ufo-data#164]
I am adding cloud_liquid_water as a bias correction predictor for GMI/GPM. The cloud is a mean cloud amount value of retrieved from observations and simulations. These two retrievals are compared to determine whether this mean cloud predictor should be used for data at the observed location. In other words, this predictor is not used for all GMI observations. Therefore, these two clouds, not the mean value, are needed. In order to make source codes and configurations simple, I tend to use the "CLWRetMW " function in a new subroutine in "CloudLiquidWater.h":

static void clwDerivative_gmi(const ObsFilterData &,
std::vector &);

Here is a section of my configuration in my yaml file. :

obs bias:
input file: Data/ufo/testinput_tier_1/gsi.x0044j.bc.gmi_gpm.2020-12-14T21:00:00Z.satbias.nc4
variational bc:
predictors:
- name: constant
- name: lapse_rate
order: 2
tlapse: &gmitlap Data/ufo/testinput_tier_1/gsi.x0044j.bc.gmi_gpm.2020-12-14T21:00:00Z.tlapse.txt
- name: lapse_rate
tlapse: *gmitlap
- name: emissivity
- name: cloud_liquid_water
satellite: GPM
options:
clwret_ch37v: 6
clwret_ch37h: 7
clwret_types: [ObsValue, HofX]
....

My changes are added in the attached CloudLiquidWater.h and CloudLiquidWater.cc (renamed as *txt). Here is the error message when I tried to build UFO:
[ 37%] Building CXX object ufo/src/ufo/CMakeFiles/ufo.dir/predictors/CloudLiquidWater.cc.o
/discover/nobackup/jjin3/jedi/fv3-bundle/ufo/src/ufo/predictors/CloudLiquidWater.cc(182): error: type name is not allowed
CloudLiquidWater::clwDerivative_gmi( ObsFilterData,
^
/discover/nobackup/jjin3/jedi/fv3-bundle/ufo/src/ufo/predictors/CloudLiquidWater.cc(242): error: declaration is incompatible with "void ufo::CloudLiquidWater::clwDerivative_gmi(const ufo::ObsFilterData &, std::vector<float, std::allocator> &)" (declared at line 80 of "/discover/nobackup/jjin3/jedi/fv3-bundle/ufo/src/ufo/predictors/CloudLiquidWater.h")
void CloudLiquidWater::clwDerivative_gmi(const ObsFilterData & in,
^
compilation aborted for /discover/nobackup/jjin3/jedi/fv3-bundle/ufo/src/ufo/predictors/CloudLiquidWater.cc (code 2)
ufo/src/ufo/CMakeFiles/ufo.dir/build.make:730: recipe for target 'ufo/src/ufo/CMakeFiles/ufo.dir/predictors/CloudLiquidWater.cc.o' failed
make[2]: *** [ufo/src/ufo/CMakeFiles/ufo.dir/predictors/CloudLiquidWater.cc.o] Error 2
CMakeFiles/Makefile2:15843: recipe for target 'ufo/src/ufo/CMakeFiles/ufo.dir/all' failed
make[1]: *** [ufo/src/ufo/CMakeFiles/ufo.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

Is there any suggestions to solve this problem? Thanks.

[gmi_qc_filters.yaml.txt](https://github.com/JCSDA-internal/ufo-data/files/8578074/gmi_qc_filters.yaml.txt)
[CloudLiquidWater.h.txt](https://github.com/JCSDA-internal/ufo-data/files/8578075/CloudLiquidWater.h.txt)
[CloudLiquidWater.cc.txt](https://github.com/JCSDA-internal/ufo-data/files/8578076/CloudLiquidWater.cc.txt)

**Comment by shlyaeva** [comment]
From looking at the code, `clwDerivative_gmi` method expects two arguments: an object of type `ObsFilterData` , and an object of `std::vector` for the output data.

```c++
void CloudLiquidWater::clwDerivative_gmi(const ObsFilterData & in,
                                           std::vector<float> & out) const
```

`clwDerivative_gmi` is called on line 242 of `CloudLiquidWater.cc` in the following way, which is where the compilation error occurs:

```c++
  CloudLiquidWater::clwDerivative_gmi( ObsFilterData,
                                          clw);
```

The second argument, I think, is passed correctly: `clw` is declared on line 172 as an `std::vector`. The first one, however, needs to be an object (variable) name, and not a class (type) name, because it is a call to a method (function). I think the intended object is probably `CLWRetMW` (which is passed to `CloudLiquidWater::compute` on line 91). I would recommend uncommenting the lines that pass `ObsFilterData` to `compute` both in `.h` and `.cc` files, and changing the call on line 242 to:

```c++
  CloudLiquidWater::clwDerivative_gmi( CLWRetMW,
                                          clw);
```

I think this would fix this compilation error.

**Comment by danholdaway** [comment]
@shlyaeva @rhoneyager I think there is a design question here. @gmao-jjin3 is finding that in order to perform the bias correction that is needed it is necessary to pass the `ObsFilterData` object into the compute method of the predictor. But since this is an override method that would require changes to the `PredictorBase` class, and I presume all the classes that also inherit from it. We also haven't looked upstream to where `compute` is called from to determine if the `ObsFilterData` object is available to be passed in. Since the changes would quickly spread to a number of files and relies somewhat on knowledge of whether the object is available to be passed I think the real question here is whether that is something that makes sense to do before we try and tackle it?

**Comment by gmao-yzhu** [comment]
I'm not sure why ObsFilterData is needed at the bias correction step, I think the arguments in the original predictorBase interface should be sufficient. I need to read Jianjun's code carefully in order to understand what the problem is.

**Comment by gmao-jjin3** [comment]
Thank you, @shlyaeva .  I got an error after un-commenting the lines passing "ObsFilterData"like: 
/discover/nobackup/jjin3/jedi/fv3-bundle/ufo/src/ufo/predictors/CloudLiquidWater.h(65): error: member function declared with "override" does not override a base class member
    void compute(const ioda::ObsSpace &,
         ^
 As Dan told me, we have to change the settings of the base class in other predictors in order to pass it correctly, which is a broad change we may want to avoid.
 
Anyway, I am thinking of copying part of the code in **_CLWRetMW.cc_** into **_CloudLiquidWater.cc_** since what I want are GMI cloud retrieval functions in all-sky conditions @gmao-yzhu .

**Comment by shlyaeva** [comment]
> @shlyaeva @rhoneyager I think there is a design question here. @gmao-jjin3 is finding that in order to perform the bias correction that is needed it is necessary to pass the `ObsFilterData` object into the compute method of the predictor. But since this is an override method that would require changes to the `PredictorBase` class, and I presume all the classes that also inherit from it. We also haven't looked upstream to where `compute` is called from to determine if the `ObsFilterData` object is available to be passed in. Since the changes would quickly spread to a number of files and relies somewhat on knowledge of whether the object is available to be passed I think the real question here is whether that is something that makes sense to do before we try and tackle it?

I see! I am not sure. @rhoneyager what do you think?

**Comment by rhoneyager** [comment]
```cpp
  void compute(const ioda::ObsSpace &,
               const GeoVaLs &,
               const ObsDiagnostics &,
               const ObsBias &,
               ioda::ObsVector &) const override;
```

By passing ```ObsFilterData```, you could also consolidate the ```ObsSpace```, ```GeoVaLs```, and ```ObsDiagnostics``` parameters. I'll admit that ```ObsFilterData``` has expanded far beyond its initial design goal of providing a unified view of data for filters and ObsFunctions. (Perhaps we should rename it to something like ```ObsDataView```?)

I think the need for ```ObsFilterData``` is a side effect of the original source of the code. I expect that you can make the calculation without using it, as all of the inputs to ```ObsFilterData``` (e.g. the ```ObsSpace```, ```GeoVaLs```, etc.) are already available in the compute call. It could be nice, though, to switch to passing ```ObsFilterData``` to promote conformity and to avoid splicing the original algorithm across separate files.

**Comment by gmao-yzhu** [comment]
As said by @rhoneyager there are benefits of switching to ObsFilterData to promote conformity, but the original interface is much more clear (without another upper data layer).

**Comment by gmao-yzhu** [comment]
@gmao-jjin3 In CloudLiquid Water, there are actually two slightly different ways. One is for SSMIS, it uses an obsfunction from filters, which is similar to what you intended to do; the other is for AMSU-A and ATMS, cloud quantity is calculated directly here and saved for later use in the filter. Since cloud index in your case is used first in bias correction before it is used in filters, either way could be okay.

**Comment by gmao-jjin3** [comment]
I attached my updated codes without passing "ObsFilterData". However, it has trouble in getting vectors such as ObsBias or ObsBiasData, HofX, and these values of "brightness_temperature_assuming_clear_sky_"  when a test is conducted.  It can use odb.get_db() to get "ObsValue", but cannot get above variables.  Any suggestions about how to get those values in the following lines? Thanks.

    std::vector<float> bias_37v(nlocs), bias_37h(nlocs);
    odb.get_db("ObsBiasData", "brightness_temperature_" + std::to_string(channels[jch37v]), bias_37v);
    odb.get_db("ObsBiasData", "brightness_temperature_" + std::to_string(channels[jch37h]), bias_37h);

....
    std::vector<float> bt_hofx_37v(nlocs), bt_hofx_37h(nlocs);
    // Error: cannnot open "HofX/brightness_temperature"
    odb.get_db("HofX", "brightness_temperature_" + std::to_string(channels[jch37v]), bt_hofx_37v);
    odb.get_db("HofX", "brightness_temperature_" + std::to_string(channels[jch37h]), bt_hofx_37h);

    std::vector<float> bt_clr_37v(nlocs), bt_clr_37h(nlocs);
    // Error:  no such variable "brightness_temperature_assuming_clear_sky"
    ydiags.get(bt_clr_37v, "brightness_temperature_assuming_clear_sky_" + std::to_string(channels[jch37v]));
    ydiags.get(bt_clr_37h, "brightness_temperature_assuming_clear_sky_" + std::to_string(channels[jch37h]));


[CloudLiquidWater.cc.txt](https://github.com/JCSDA-internal/ufo-data/files/8612531/CloudLiquidWater.cc.txt)
[CloudLiquidWater.h.txt](https://github.com/JCSDA-internal/ufo-data/files/8612532/CloudLiquidWater.h.txt)

**Comment by gmao-yzhu** [comment]
You may follow what was done for AMSU-A for getting Tb and bias correction coef inside the code.

**Comment by gmao-jjin3** [comment]
Thank @gmao-yzhu for the suggestion. I am able to add the constant and scan_position bias corrections upon **Hofx** and the simulated "brightness_temperature_assuming_clear_sky". It is still needed to add the bias correction terms using temperature lapse (lapse_rate, and lapse_rate_order_2) before we can reproduce these GPM cloud indexes made in GSI. However, it looks to me there is not a good way to do that as we have done for the constant and scan_position  bias correction terms by more or less copying codes over there. Is there a way to use the function **LapseRate.cc** in my new **CloudLiquidWater.cc** (a new version is attached)?  Thanks.

 Here is the BC part in my yaml file:    
  ```
obs bias:
    input file: Data/ufo/testinput_tier_1/gsi.x0044j.bc.gmi_gpm.2020-12-14T21:00:00Z.satbias.nc4
    variational bc:
      predictors:
      - name: constant
      - name: lapse_rate
        order: 2
        tlapse: &gmitlap Data/ufo/testinput_tier_1/gsi.x0044j.bc.gmi_gpm.2020-12-14T21:00:00Z.tlapse.txt
      - name: lapse_rate
        tlapse: *gmitlap
      - name: emissivity
      - name: cloud_liquid_water
        satellite: GPM
        ch37v: 6
        ch37h: 7
      - name: cloud_liquid_water
        satellite: GPM
        options:
        ch37v: 6
        ch37h: 7
        order: 2
      - name: scan_angle
        var_name: scan_position
        order: 4
      - name: scan_angle
        var_name: scan_position
        order: 3
      - name: scan_angle
        var_name: scan_position
        order: 2
      - name: scan_angle
        var_name: scan_position

```
Here is the BC part  where I'd like to add the lapse_rate BC terms in my  CloudLiquidWater.cc:    
```

207     std::vector<float> bias_37v(nlocs), bias_37h(nlocs);
208     const Predictors & predictors = biascoeffs.predictors();
209     const std::size_t npreds = predictors.size();
210     double beta1, beta2;
211     std::vector<float> scanangle(nlocs,0.0);
212     odb.get_db("MetaData", "scan_position", scanangle);
213     for (std::size_t jloc = 0; jloc < nlocs; ++jloc) {
214       // constant term
215       beta1 = biascoeffs(0, channels_[jch37v]-1);
216       beta2 = biascoeffs(0, channels_[jch37h]-1);
217       bias_37v[jloc] = beta1;
218       bias_37h[jloc] = beta2;
219       // scan_position term
220       for (std::size_t jord = 0; jord < 4; ++jord) {
221         beta1 = biascoeffs(npreds-jord-1, channels_[jch37v]-1);
222         beta2 = biascoeffs(npreds-jord-1, channels_[jch37h]-1);
223         bias_37v[jloc] += beta1 * pow(scanangle[jloc] * Constants::deg2rad, jord+1);
224         bias_37h[jloc] += beta2 * pow(scanangle[jloc] * Constants::deg2rad, jord+1);
225       }
226       bt_hofx_37v[jloc] += bias_37v[jloc];
227       bt_hofx_37h[jloc] += bias_37h[jloc];
228       bt_clr_37v[jloc]  += bias_37v[jloc];
229       bt_clr_37h[jloc]  += bias_37h[jloc];
230     }

```
[CloudLiquidWater.cc.txt](https://github.com/JCSDA-internal/ufo-data/files/8662519/CloudLiquidWater.cc.txt)
[CloudLiquidWater.h.txt](https://github.com/JCSDA-internal/ufo-data/files/8662520/CloudLiquidWater.h.txt)

**Comment by gmao-yzhu** [comment]
@huishao-r @BenjaminRuston Per request, I added you to this issue. Also, for more information on why bias correction class was added in the calculation of predictors, please see PR #1899 (https://github.com/JCSDA-internal/ufo/pull/1899). Technically, jianjun can add the code for tlap bias terms in CloudLiquidWater.cc to calculate the bias-corrected variables for CLW index, just as the same way that constant and angle bias terms were calculated, it is just that a more elegant way might be used.

**Comment by shlyaeva** [comment]
Has this issue been resolved?

**Comment by gmao-jjin3** [comment]
> Has this issue been resolved?

Yes, it has.  Thanks for asking. @shlyaeva
