### ISSUE TITLE
Change air_pressure group name to ObsValue

### ISSUE THREAD

**Issue by james-cotton** [JCSDA-internal/ufo-data#237]
## Description
Change the group name of air_pressure from MetaData to ObsValue as per the naming convention. 

This will make the upcoming variable name code sprint simpler, since we won't have to deal with the change in variable name and group name at the same time (this is the only change in group).

**Comment by symoore90** [comment]
is this still relevant? @james-cotton

**Comment by james-cotton** [comment]
Hi @symoore90 we can close this as no longer needed
