### ISSUE TITLE
SPRINT: Missing files in update

### ISSUE THREAD

**Issue by mikecooke77** [JCSDA-internal/ufo-data#252]
## Description

Quite a few files were missed by the first batch upgrader.  I have created a new branch from the latest sprint branch and pushed a bulk upgrade of files.  You can see this at:
https://github.com/JCSDA-internal/ufo-data/tree/feature/sprint-ioda-converters-mikecooke77-5

I have not updated any geoval or obsdiag files.  If there are any erroneous ones the proof will be in the testing.

**Comment by mikecooke77** [comment]
We've also noticed that geoval and obsdiag files have also been updated.  We think this is erroneous.

**Comment by shlyaeva** [comment]
@mikecooke77 do you know if this has been resolved?

I'm also briefly looking into what happens if we update the ufo-data files now again with the latest upgrader (although there are still a couple PRs to go into ioda, so it may be best to wait for that).

**Comment by mikecooke77** [comment]
I think this is now fixed yes.  I think it should be OK to run the upgrader over the files again but I would be tempted to leave this until after the 17th merge just in case things go wrong.  We did have some strange errors which took a while to fix initially.

**Comment by shlyaeva** [comment]
sounds good, I agree. I'm closing this issue since it's fixed.
