### ISSUE TITLE
BUG: Possible redundant variables left over from the conversion to JEDI2

### ISSUE THREAD

**Issue by cpelley** [JCSDA-internal/ufo-data#3]
## Current behaviour (describe the bug) / To Reproduce

```
$ ncdump -h filters_testdata.nc4
```

```
netcdf filters_testdata {
dimensions:
	nlocs = 10 ;
	ndatetime = 20 ;
	nstring = 10 ;
variables:
	float ndatetime(ndatetime) ;
		ndatetime:suggested_chunk_dim = 100LL ;
	float nlocs(nlocs) ;
		nlocs:suggested_chunk_dim = 100LL ;
	float nstring(nstring) ;
		nstring:suggested_chunk_dim = 100LL ;
...
```

Note the presence of the `ndatetime` and `nstring` variables which should no longer be required?

## Expected behaviour

Simple deletion of these variables?

**Comment by cpelley** [comment]
You think a change to [upgrade](https://github.com/JCSDA-internal/ioda/tree/feature/ioda-v2/src/engines/ioda/src/mains/upgrade) to automatically remove these redundant variables would be desirable?

**Comment by shlyaeva** [comment]
@cpelley has this issue been resolved?

**Comment by cpelley** [comment]
Thanks for the prod. @shlyaeva.  Apologies for not getting onto this - I think this is rather low hanging fruit.
Looks like the issue still remains.

Some existing test files still contain redundant variables AND also the upgrader still keeps such variables when creating new files (upgrading JEDI1 files):

```
$ ./ioda-upgrade.x /path/to/git/jedi/ufo-bundle/ioda-data/testinput_tier_1/upgrader_amsua_n19.nc4 output.nc
$ ncdump -h output.nc

netcdf  output{
dimensions:
        ...
        ndatetime = 20 ;
        ...
        nstring = 50 ;
        ...
variables:
        ...
        float ndatetime(ndatetime) ;
                ndatetime:suggested_chunk_dim = 100LL ;
        ...
        float nstring(nstring) ;
                nstring:suggested_chunk_dim = 100LL ;
        ...
...
}
```

**Comment by shlyaeva** [comment]
This will be fixed once `feature/sprint-ioda-converters` branch is merged in next Tuesday (I just verified). I'm going to close this issue now even though the fix will be in a few days.
