### ISSUE TITLE
[Bug?] on SMAP obs file

### ISSUE THREAD

**Issue by HamidehGMAO** [JCSDA-internal/ufo-data#34]
## Current behavior (describe the bug)
looking at smap obs file it seems something is wrong with the obs file. the dimension of  brightness_temperature is (nlocs, nlocs) instead of (nlocs, nchans), and in the dimensions, the nchans is missing and instead we have two nlocs. any idea?

netcdf smap_obs_2018041500_m {
dimensions:
	nlocs = 100 ;
	nlocs = 100 ;
	nrecs = 100 ;
	nvars = 4 ;
	nstring = 50 ;
	ndatetime = 20 ;
variables:
	int nchans(nlocs) ;
		nchans:suggested_chunk_dim = 4LL ;
	float ndatetime(ndatetime) ;
		ndatetime:suggested_chunk_dim = 100LL ;
	float nlocs(nlocs) ;
		nlocs:suggested_chunk_dim = 100LL ;
	float nrecs(nrecs) ;
		nrecs:suggested_chunk_dim = 100LL ;
	float nstring(nstring) ;
		nstring:suggested_chunk_dim = 100LL ;
	float nvars(nvars) ;
		nvars:suggested_chunk_dim = 100LL ;

// global attributes:
		:nrecs = 100 ;
		:_ioda_layout_version = 0 ;
		:satellite = "smap" ;
		:nvars = 4 ;
		:date_time = 2018041500 ;
		:nlocs = 100 ;
		:sensor = "radiometer" ;
		string :_ioda_layout = "ObsGroup" ;

group: MetaData {
  variables:
  	float height_above_mean_sea_level(nlocs) ;
  	float latitude(nlocs) ;
  	float longitude(nlocs) ;
  	int record_number(nlocs) ;
  	float scan_position(nlocs) ;
  	float sensor_azimuth_angle(nlocs) ;
  	float sensor_view_angle(nlocs) ;
  	float sensor_zenith_angle(nlocs) ;
  	float solar_azimuth_angle(nlocs) ;
  	float solar_zenith_angle(nlocs) ;
  	float sss(nlocs) ;
  	float time(nlocs) ;
  } // group MetaData

group: ObsError {
  variables:
  	float brightness_temperature(nlocs, nlocs) ;
  } // group ObsError

group: ObsValue {
  variables:
  	float brightness_temperature(nlocs, nlocs) ;
  } // group ObsValue

group: PreQC {
  variables:
  	int brightness_temperature(nlocs, nlocs) ;
  } // group PreQC

group: VarMetaData {
  variables:
  	float ObsError(nvars) ;
  	int gsi_use_flag(nvars) ;
  	float mean_lapse_rate(nvars) ;
  	int polarization(nvars) ;
  	float sensor_band_central_radiation_frequency(nvars) ;
  	float sensor_band_central_radiation_wavenumber(nvars) ;
  	int sensor_channel(nvars) ;
  } // group VarMetaData
}

**Comment by shlyaeva** [comment]
@HamidehGMAO has this issue been resolved?

**Comment by HamidehGMAO** [comment]
@shlyaeva I don't think so. I can fix this obs file, but I was wondering if there was a bug in the ioda update that caused this. @srherbener Do you know what has happened here in converting the data for smap?

**Comment by srherbener** [comment]
Thanks for reporting this. It looks like a fault in the upgrader. I'll look into this and let you know.

**Comment by srherbener** [comment]
This was likely a defect that once existed in the upgrader, and fortunately appears to be fixed in the latest version of the upgrader.

I've regenerated a new SMAP obs file (using the current upgrader) and tried this file with both ioda and ufo tests. All ioda and ufo tests pass with the new (fixed) file.

Note that there is a broken SMAP obs file in both ioda-data and ufo-data so I've put the new, fixed version in both and tested it.

I will create PR's for ufo-data and ioda-data with the new SMAP obs file.
